# Generated by Django 4.2.13 on 2024-09-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.TextField(null=True)),
                ('pub_url', models.CharField(blank=True, max_length=200)),
                ('citation', models.CharField(blank=True, max_length=200)),
                ('author', models.TextField(blank=True, null=True)),
                ('pub_year', models.IntegerField(blank=True, null=True)),
                ('google_scholar_id', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
